### ISSUE TITLE
Generated events change between versions

### ISSUE THREAD

**Issue by dcervenkov** [GooFit/AmpGen#21]
I recently checked out the master branch and generated some more MC through AmpGen. To my surprise, the results were significantly different than my older AmpGen MC, even with the exact same option files and arguments. 

Results with the same seed differ (much more than stat. fluctuations, as well); see the distributions of two-particle invariant masses from D0 -> KKππ:
![ampgen_old_new](https://user-images.githubusercontent.com/23052054/122640141-b6f4e600-d0f5-11eb-93ab-a56568e482ac.png)

The option files used to generate the decays can be found [here](https://cernbox.cern.ch/index.php/s/ryUZz3xa7gMZjHV).

I did a `git bisect` and `d3ec082ed3` is the first "bad" commit.

**Comment by tevans1260** [comment]
I took a look: the problem is caused by the logic to add CP conjugate amplitudes, which broke for additional parameters of particles such as masses, widths and radii ( the radii being the cause of the problem here) It is now fixed in the master. 

I noticed that there is also additional amplitudes being added by the CP conjugation logic related to conjugating the initial state (things with decay descriptors that start with D{Dbar0{D0{ ) - I should fix this properly by adding the conjugated quasiparticles explicitly, but this is a little bit nontrivial. For now I added a parameter to forbid adding conjugates for specific particles which will be useful to have anyway: AddCPConjugate::Forbid. If you add the line 
`AddCPConjugate::Forbid D `
to the options it will remove these additional amplitudes (that probably will result in something like an erroneous factor of 2 in the mixing..)

**Comment by dcervenkov** [comment]
Thanks for looking into it, @tevans1260! Do I understand it correctly, that d3ec082ed3 caused both issues, and using current master and `AddCPConjugate::Forbid D` will result in the same MC as before? Or was the second issue present previously as well?

**Comment by tevans1260** [comment]
No problem! So d3ec082 only caused the issue with the particle radii, the other issue was present before. 

Taking a closer look, I'm not sure it will result in identical MC as before, but it should now result in producing events that the simulating the flavour tagged case is the same as turning off mixing, which is the desired result. 

I'm a bit surprised the second issue wasn't caught sooner [ i.e. by the B->D[kkpipi] h folks] as it always would have done this .

**Comment by dcervenkov** [comment]
Should the INFO lines change when using `AddCPConjugate::Forbid D`? I still see lines like
```
D{Dbar0{D0{KPi10[FOCUS.Kpi]{K+,pi-},KPi00[FOCUS.Kpi]{K-,pi+}}}}
```

I'm not quite sure what you mean by the following:
> Taking a closer look, I'm not sure it will result in identical MC as before, but it should now result in producing events that the simulating the flavour tagged case is the same as turning off mixing, which is the desired result.

You talk about turning off the mixing - is `AddCPConjugate::Forbid D` equivalent to setting x = y = 0 when `D[TD]{D0} = -1 * ( y + i * x )`?

**Comment by tevans1260** [comment]
Strange - yes the intended effect was that those lines should be gone.. The debug mode is also a bit broken at the moment for free functions (https://www.youtube.com/watch?v=Jne9t8sHpUc) - I just pushed to the master with some debug messages explicitly enabled - could you try again and post the full log? 

> I'm not quite sure what you mean by the following:
... 
You talk about turning off the mixing - is AddCPConjugate::Forbid D equivalent to setting x = y = 0 when D[TD]{D0} = -1 * ( y + i * x )?

Sorry was unclear, AddCPConjugate::Forbid D prevents AmpGen from taking any rule where the head is a D (your quasiparticle), and producing the conjugated rule. The conjugated quasiparticle defaults to the conjugate of the actual particle. In this case the problem is the rule: 

`D{Dbar0}`

produces the conjugate rule 

`Dbar0{D0}` 

as 'D' is just a label for 'D0' - this then contributes to your final state. This is a bug in how quasiparticles are implemented, but it isn't obvious to me how this should be fixed .. hence the quick fix.

**Comment by tevans1260** [comment]
Should now work as expected 'out-of-the-box' i.e. without explicitly forbidding conjugating these amplitudes.

**Comment by dcervenkov** [comment]
> Sorry was unclear, AddCPConjugate::Forbid D prevents AmpGen from taking any rule where the head is a D (your quasiparticle), and producing the conjugated rule. The conjugated quasiparticle defaults to the conjugate of the actual particle. In this case the problem is the rule:

>`D{Dbar0}`

>produces the conjugate rule

>`Dbar0{D0}`

>as 'D' is just a label for 'D0' - this then contributes to your final state. This is a bug in how quasiparticles are implemented, but it isn't obvious to me how this should be fixed .. hence the quick fix.

Thanks for the explanation! This is indeed not what one would expect.

I did some testing and don't observe any difference between 51d4a4815f, 2acc87521a (not in master anymore because of force push to master), 1a4d280314, either with or without `AddCPConjugate::Forbid D` - in all six cases, identical files are produced. This is not what is expected, right?

Here's a [log.txt](https://github.com/GooFit/AmpGen/files/6709257/log.txt) from 51d4a4815f with `AddCPConjugate::Forbid D` in the options file.

**Comment by tevans1260** [comment]
FYI, the relevant commit for this working by default is c5b9a13. Could you check these changes are picked up in your local copy?Anyway, I can no longer reproduce this problem; could you do a clean pull and build and try again?

**Comment by dcervenkov** [comment]
OK, my bad! I was accidentally running a different AmpGen than I was compiling. I now see a difference.

However, I also see a difference with commit 51d4a48 with and without `AddCPConjugate::Forbid D`. Here are the logs: [log_with.txt](https://github.com/GooFit/AmpGen/files/6710480/log_with.txt) and [log_without.txt](https://github.com/GooFit/AmpGen/files/6710481/log_without.txt).

Basically, the difference is that without the `Forbid` line, there are lines like this:
```
D{D0[D]{K*(1680)0{K+,pi-},K*(892)bar0{K-,pi+}}}
```
which are gone when using `Forbid`.

Did I misunderstand that the `Forbid` line should be active by default since c5b9a13?

**Comment by tevans1260** [comment]
Strange, yes the forbid line is 'default' since c5b9a13, so these lines are gone for me (i.e. log_with.txt is ~ what I get without the explicit forbid line) - is this still an issue?

**Comment by dcervenkov** [comment]
Yes, this is still an issue with a freshly checked out and built 51d4a48. I also tried with c5b9a13 and also see the difference. Maybe there is something peculiar about my options file; are those lines gone for you when using the option files from the first post?

**Comment by tevans1260** [comment]
I see the problem [I'd left the explicit forbid line in the test script] and had forgotten to add the line to prevent generating a set of rules for conjugates without distinct anti particles. Anyway, it should now be fixed in the master.

**Comment by dcervenkov** [comment]
I can confirm it is fixed now, thanks!
